### ISSUE TITLE
flutter_inappwebview for more andvance WebView func.

### ISSUE THREAD

**Issue by PrimozRatej** [luke-/app#30]

**Comment by PrimozRatej** [comment]
https://pub.dev/packages/flutter_inappwebview

**Comment by PrimozRatej** [comment]
The impl. of custom headers for every request is possible for  [InAppWebView](https://pub.dev/packages/flutter_inappwebview).

![image](https://user-images.githubusercontent.com/10835179/217035573-948d2a32-695b-418c-89b9-1cd62faad8af.png)

**Comment by luke-** [comment]
@PrimozRatej This looks very promising! From the source, it looks like the header feature only affects Ajax requests. 

Many calls in the HumHub WebApp are Ajax (e.g. click from the dashboard to People page, since only a view partial is transferred here). But especially on full page requests (e.g. initial dashboard request) the Header would be important. Can you check/confirm this?

I've added a test link on the example site:

![image](https://user-images.githubusercontent.com/4736168/217079267-65496ead-e576-41ed-8692-80133d22f9fc.png)
